project:
  type: website

website:
  title: "<img src='/images/logo.png' alt='earth Symbol' style='width: 2.6em; height: 2.2em; border-radius: 30%;'> <b>Premier League Performance Metrics and Results</b>"
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO523-S24/project-01
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: default
    toc: true

execute:
  freeze: auto
